# Generated by Django 5.2.8 on 2025-12-11 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rag', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='latestnews',
            options={'ordering': ['-news_collection_date']},
        ),
        migrations.AddField(
            model_name='latestnews',
            name='company_name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='latestnews',
            name='image_url',
            field=models.URLField(blank=True, max_length=2048, null=True),
        ),
        migrations.AddField(
            model_name='latestnews',
            name='sentiment',
            field=models.CharField(default='neutral', max_length=20),
        ),
        migrations.AddField(
            model_name='latestnews',
            name='source',
            field=models.CharField(blank=True, default='Unknown', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='latestnews',
            name='news_collection_date',
            field=models.DateTimeField(),
        ),
    ]
