# Generated by Django 5.2.8 on 2025-12-22 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rag', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='realized_profit',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=20),
        ),
        migrations.AlterField(
            model_name='latestnews',
            name='url',
            field=models.URLField(blank=True, max_length=2048, null=True, unique=True),
        ),
    ]
