# Generated by Django 5.2.8 on 2025-12-16 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rag', '0002_alter_latestnews_options_latestnews_company_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='latestnews',
            name='max_similarity_score',
            field=models.FloatField(db_index=True, default=0.0),
        ),
        migrations.AddField(
            model_name='latestnews',
            name='view_count',
            field=models.IntegerField(default=0),
        ),
    ]
