# Generated by Django 5.2.8 on 2025-11-26 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rag', '0002_follow_historicalnews_latestnews_post_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalnews',
            name='url',
            field=models.URLField(blank=True, max_length=2048, null=True),
        ),
        migrations.AddField(
            model_name='latestnews',
            name='url',
            field=models.URLField(blank=True, max_length=2048, null=True),
        ),
    ]
