# Generated by Django 5.2.8 on 2025-11-30 06:05

import pgvector.django.vector
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rag', '0003_historicalnews_url_latestnews_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalnews',
            name='body_embedding_vector',
            field=pgvector.django.vector.VectorField(dimensions=1536),
        ),
        migrations.AlterField(
            model_name='latestnews',
            name='body_embedding_vector',
            field=pgvector.django.vector.VectorField(dimensions=1536),
        ),
    ]
