# Generated by Django 5.2.8 on 2025-12-18 06:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rag', '0003_alter_user_mileage'),
        ('rag', '0003_latestnews_max_similarity_score_and_more'),
    ]

    operations = [
    ]
