# Generated by Django 5.2.8 on 2025-12-18 08:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rag', '0004_merge_20251218_1537'),
        ('rag', '0004_merge_20251218_1546'),
    ]

    operations = [
    ]
