# Generated by Django 5.2.8 on 2025-12-21 09:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rag', '0004_merge_20251218_1713'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='stockprice',
            unique_together={('company', 'record_time')},
        ),
    ]
