# Generated by Django 5.2.8 on 2025-12-03 07:38

import pgvector.django.vector
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rag', '0004_alter_historicalnews_body_embedding_vector_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalnews',
            name='body_embedding_vector',
            field=pgvector.django.vector.VectorField(blank=True, dimensions=1536, null=True),
        ),
        migrations.AlterField(
            model_name='historicalnews',
            name='impacted_ticker',
            field=models.CharField(db_index=True, max_length=500, null=True),
        ),
    ]
