# Generated by Django 5.2.8 on 2025-12-21 09:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rag', '0005_alter_stockprice_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='watchlistitem',
            name='company',
            field=models.ForeignKey(blank=True, db_column='company_code', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='watchlist_items', to='rag.company'),
        ),
        migrations.AlterModelTable(
            name='watchlistitem',
            table='watchlist',
        ),
    ]
