# Generated by Django 5.2.8 on 2025-12-09 11:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rag', '0005_alter_historicalnews_body_embedding_vector_and_more'),
        ('rag', '0006_post_ticker_post_updated_at_comment_postlike'),
    ]

    operations = [
    ]
